version: '3.8'
volumes:
  data:
services:
  database:
    env_file:
     - .env
    image: "${DATABASE_NAME}"
    ports:
     - 5432:5432
    environment:
     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
     - data:/var/lib/postgresql/data


 